# Generated by Django 2.1.7 on 2019-04-24 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_title', models.CharField(max_length=300)),
                ('thread_date', models.DateField(auto_now_add=True)),
                ('thread_content', models.CharField(max_length=5000)),
                ('thread_user', models.CharField(max_length=100)),
                ('thread_replies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Thread')),
            ],
        ),
    ]
