# Generated by Django 2.1.7 on 2019-04-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread_replies',
            new_name='replies',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='thread',
            name='is_master',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
