# Generated by Django 2.1.7 on 2019-04-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20190423_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
