# Generated by Django 2.1.7 on 2019-04-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20190423_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='replies',
        ),
        migrations.AddField(
            model_name='thread',
            name='replies',
            field=models.ManyToManyField(null=True, related_name='_thread_replies_+', to='threads.Thread'),
        ),
    ]
