# Generated by Django 2.1.7 on 2019-04-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20190423_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='replies',
            field=models.ManyToManyField(related_name='_thread_replies_+', to='threads.Thread'),
        ),
    ]
