# Generated by Django 2.1.7 on 2019-04-24 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20190423_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='replies',
        ),
        migrations.AddField(
            model_name='thread',
            name='replies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threads.Thread'),
        ),
    ]
