# Generated by Django 2.1.7 on 2019-04-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_auto_20190423_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='replies',
            new_name='parent',
        ),
    ]
